"""Generate the solution walkthrough (.docx) from the artefacts.

    python scripts/build_walkthrough.py

Every number in the document is read from artifacts/published at build time. None are
typed in. That is deliberate and it is the answer to the class of bug that has bitten
this project twice already: a retired filter and a stale cache each produced numbers for
code that never ran, and both were caught by a count looking wrong rather than by a test.
A document typed by hand is the same failure with no test at all.

Where an artefact is missing, the section says so rather than being omitted or filled in.

Built with python-docx rather than docx-js so it can run as a stage of the pipeline and
be regenerated by scripts/reproduce.py on a clean clone.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

from adl.common.config import source_digest
from adl.common.contracts import coverage_report
from adl.common.paths import ARTIFACTS_DIR, FIXTURES_DIR

PUBLISHED = ARTIFACTS_DIR / "published"
OUT = ARTIFACTS_DIR / "AI_Defense_Lab_Walkthrough.docx"

INK = RGBColor(0x14, 0x14, 0x0F)
MUTED = RGBColor(0x4E, 0x4E, 0x46)
SPOT = RGBColor(0x0F, 0x5C, 0x4A)
WARN = RGBColor(0x94, 0x29, 0x0C)


def load(name: str) -> dict[str, Any] | None:
    path = PUBLISHED / name
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def pct(x: float | None, dp: int = 1) -> str:
    return "n/a" if x is None else f"{x * 100:.{dp}f}%"


def setup(doc: Document) -> None:
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10.5)
    style.font.color.rgb = INK
    style.paragraph_format.space_after = Pt(7)
    style.paragraph_format.line_spacing = 1.15


def caption(doc: Document, text: str) -> None:
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(8.5)
    run.font.color.rgb = MUTED
    run.italic = True
    p.paragraph_format.space_after = Pt(11)


def callout(doc: Document, text: str, colour: RGBColor = SPOT) -> None:
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.color.rgb = colour
    run.font.size = Pt(11)
    p.paragraph_format.space_before = Pt(4)
    p.paragraph_format.space_after = Pt(9)


def table(doc: Document, headers: list[str], rows: list[list[str]], widths: list[float] | None = None):
    t = doc.add_table(rows=1, cols=len(headers))
    t.style = "Table Grid"
    t.alignment = WD_TABLE_ALIGNMENT.LEFT
    for i, h in enumerate(headers):
        cell = t.rows[0].cells[i]
        cell.text = ""
        run = cell.paragraphs[0].add_run(h)
        run.bold = True
        run.font.size = Pt(9)
    for row in rows:
        cells = t.add_row().cells
        for i, value in enumerate(row):
            cells[i].text = ""
            run = cells[i].paragraphs[0].add_run(str(value))
            run.font.size = Pt(9)
    doc.add_paragraph()
    return t


def build() -> Path:
    manifest = load("run_manifest.json")
    loop = load("run_manifest_loop.json")
    attacks = json.loads((FIXTURES_DIR / "attacks.fixture.json").read_text(encoding="utf-8"))
    vectors = attacks["vectors"]
    coverage = coverage_report(vectors)

    doc = Document()
    setup(doc)

    # ---------------------------------------------------------------- cover
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = title.add_run("AI Defense Lab for Payment Security")
    run.bold = True
    run.font.size = Pt(26)
    run.font.color.rgb = INK

    sub = doc.add_paragraph()
    run = sub.add_run("Mastercard Innovation Challenge · Global Fintech Fest 2026")
    run.font.size = Pt(12)
    run.font.color.rgb = MUTED

    meta = doc.add_paragraph()
    run = meta.add_run(
        f"Team Code Ops · Solution walkthrough · {date.today():%d %B %Y}\n"
        "Repository: github.com/ananyac9820/ai-defense-lab\n"
        "Prototype: ananyac9820.github.io/ai-defense-lab"
    )
    run.font.size = Pt(10)
    run.font.color.rgb = MUTED

    if manifest:
        caption(
            doc,
            f"Every figure in this document is read from the run artefacts at build time. "
            f"Run {manifest['run_id']}, seed {manifest['seed']}, config hash "
            f"{manifest['config_hash'][:16]}. Regenerate with: python scripts/build_walkthrough.py",
        )
    else:
        callout(doc, "NO RUN ARTEFACTS FOUND. Run scripts/run_pipeline.py first.", WARN)

    # ---------------------------------------------------------------- 1
    doc.add_heading("1. What we built", level=1)
    doc.add_paragraph(
        "Three pillars connected as one cycle. A compositional grammar defines attacks as "
        "sequences of primitives. A single simulator produces every row in the ledger, "
        "legitimate and fraudulent alike. A three-level detector scores transactions, "
        "sessions and the account graph. The detector's own failures are handed to a "
        "red-team strategist, which mutates the attack set, and the cycle runs again."
    )
    doc.add_paragraph(
        "The prototype is a single scrolling dossier that reads the artefacts this pipeline "
        "emits. It holds no business logic of its own."
    )
    callout(
        doc,
        "No figure in this document was typed by hand. Every number is read from the run "
        "artefacts when the document is built.",
    )
    doc.add_paragraph(
        "The document is generated by scripts/build_walkthrough.py and rebuilt as a stage "
        "of scripts/reproduce.py, and scripts/audit_artefacts.py fails the build if any "
        "artefact it reads is older than the code that produces it, carries a different "
        "run identifier, or disagrees with the configuration in the repository. Four "
        "separate bugs in this project produced numbers for code that never ran, and all "
        "four were caught by a figure looking wrong rather than by a test. This is the "
        "control for the fifth."
    )

    # ---------------------------------------------------------------- 2 the finding
    doc.add_heading("2. The finding", level=1)
    callout(
        doc,
        "The detector does not recognise attack families. It recognises extraction.",
    )
    doc.add_paragraph(
        "We held out an attack family whose acquisition and establishment stages were "
        "entirely unseen in training, and it was detected as well as the families the "
        "detector was trained on. All fraud must eventually move money, and money movement "
        "leaves a consistent graph signature regardless of how the access was obtained."
    )
    doc.add_paragraph(
        "So we held out the extraction primitive itself, which is the test that actually "
        "probes the boundary. Detection collapsed. A vector that extracts through a "
        "merchant acquiring account, so that value never touches a peer-to-peer transfer "
        "rail, is caught roughly a third of the time while everything else is caught "
        "essentially always."
    )
    doc.add_paragraph(
        "This was discovered, not assumed. It came out of the ablation, it is falsifiable, "
        "and it is the argument for the closed loop: what finds gaps of that shape is an "
        "adversary searching the grammar, not a larger training set."
    )

    # ---------------------------------------------------------------- 3 identify
    doc.add_heading("3. Pillar 1 — Identify: the attacks", level=1)
    doc.add_paragraph(
        f"Nineteen primitives across five stages (acquire, establish, validate, extract, "
        f"obfuscate), with composition rules that make an attack a valid path through the "
        f"grammar. The grammar admits {coverage['valid_chain_space']:,} valid chains."
    )
    doc.add_paragraph(
        "That number is the space the red-team strategist searches. It is deliberately not "
        "used as a denominator: implemented-over-valid would read as failure for any "
        "grammar worth having, because a useful grammar always admits orders of magnitude "
        "more chains than a team can implement. Coverage is stated along the axes instead."
    )
    table(
        doc,
        ["Coverage measure", "Value"],
        [
            ["Attack vectors implemented", str(coverage["n_vectors"])],
            ["Primitives exercised", f"{coverage['primitives_used']} of {coverage['primitives_total']}"],
            ["Stage transitions exercised", f"{coverage['stage_transitions_used']} of {coverage['stage_transitions_possible']}"],
            ["Channels covered", f"{len(coverage['channels_covered'])} of 7"],
            ["AI capabilities covered", f"{len(coverage['capabilities_covered'])} of 7"],
            ["Taxonomy grid cells populated", f"{coverage['grid_cells_populated']} of {coverage['grid_cells_total']}"],
        ],
    )
    doc.add_paragraph(
        "Every vector carries a citation to a documented incident, and the prototype "
        "surfaces it. The grounding is what makes the feasibility claim checkable."
    )
    table(
        doc,
        ["ID", "Vector", "Channel", "Grounded in"],
        [[v["vector_id"], v["name"], v["channel"].replace("_", " "), v["source"]["doc_ref"]]
         for v in vectors],
    )
    doc.add_paragraph(
        "Deliberately excluded, and the exclusions matter as much as the list: card "
        "skimming, Magecart, counterfeit UPI apps, check fraud and forged onboarding "
        "documents. Their footprint is physical, in-page JavaScript, in-app, or an image, "
        "not a transaction, session or graph signature. Simulating them would mean "
        "inventing a data footprint we could not defend."
    )

    # ---------------------------------------------------------------- 4 generate
    doc.add_heading("4. Pillar 2 — Generate: the data", level=1)
    if manifest:
        gen0 = manifest["generations"][0]
        doc.add_paragraph(
            f"{gen0['n_transactions']:,} transactions at a "
            f"{manifest['prevalence'] * 100:.3f}% fraud base rate, with "
            f"{gen0['n_fraud']:,} fraudulent rows."
        )
    callout(
        doc,
        "Legitimate and fraudulent traffic come out of the same simulator through the same "
        "write path.",
    )
    doc.add_paragraph(
        "Mixing public-dataset rows with generated fraud produces two populations from two "
        "generating processes. They differ in timestamp precision, amount rounding, "
        "identifier format and null patterns, and a gradient-boosted tree finds that "
        "difference immediately: an F1 near 0.99 that learned only which program wrote each "
        "row. Public datasets calibrate distributions here and never supply a row."
    )
    doc.add_paragraph(
        "This is enforced rather than promised. A provenance-only classifier is trained on "
        "formatting features alone — sub-second precision, amount rounding, rupee digit, "
        "identifier ordinal — and the test asserts it performs at chance. It runs under the "
        "same time-and-account split as the real detector, because under a random split it "
        "measured burst memorisation instead and scored 0.69 while every individual feature "
        "sat at 0.50."
    )
    doc.add_paragraph(
        "Attack instances draw an abort point, a pace and an amount restraint, so the "
        "fraud population contains partial executions, declined extractions, victims who "
        "hung up before confirming, and operators careless enough to look ordinary. Without "
        "that, every chain executed at the attacker's best case and 99.3% of fraudulent rows "
        "outscored 99% of legitimate traffic with an empty band beneath them."
    )

    # ---------------------------------------------------------------- 5 defend
    doc.add_heading("5. Pillar 3 — Defend: detection results", level=1)
    if not manifest:
        callout(doc, "Pending: no run manifest.", WARN)
    else:
        gen0 = manifest["generations"][0]
        base = manifest["baseline"]["metrics"]
        floor = manifest.get("baseline_floor", {}).get("metrics")

        doc.add_heading("5.1 Where detection stops", level=2)
        doc.add_paragraph(
            "Four holdout regimes, each withholding something different. Instance recall is "
            "the comparable figure: an attack instance counts as detected when any of its "
            "rows raises an alert, which is what an alert queue actually does."
        )
        by_id = {v["vector_id"]: v for v in vectors}
        # The pipeline's own miss log, not the loop's. They used to share a filename.
        misses0 = load("misses.g0.json") or {}
        rows = []
        for row in misses0.get("per_vector", []):
            v = by_id.get(row["vector_id"])
            if not v or v.get("holdout") == "none":
                continue
            trained = {p for x in vectors if x.get("holdout") == "none" for p in x["chain"]}
            novel = [p for p in v["chain"] if p not in trained]
            rows.append([
                v["vector_id"],
                v["name"][:44],
                v.get("holdout", ""),
                ", ".join(novel) or "none (recomposition only)",
                f"{row['n_detected']}/{row['n_instances']}",
                pct(row["detection_rate"], 1),
            ])
        if rows:
            table(doc, ["ID", "Vector", "Holdout", "Novel primitives", "Detected", "Rate"], rows)
            caption(
                doc,
                "The only vector the detector misses is the one whose extraction moves off "
                "the peer-to-peer transfer rail.",
            )

        doc.add_heading("5.2 What each level of evidence contributes", level=2)
        doc.add_paragraph(
            "Mastercard's AI Garage doubled compromised-card detection by combining "
            "generative AI with graph technology over relationships between accounts, "
            "devices and cards. The graph level here is the same argument, measured."
        )
        abl = gen0.get("ablation", [])
        rows = []
        if floor:
            rows.append(["Floor: logistic regression, transaction only",
                         f"{floor['precision']:.3f}", f"{floor['recall']:.3f}",
                         f"{floor['auc_pr']:.3f}", "—"])
        rows.append(["BASELINE: tuned XGBoost, transaction only",
                     f"{base['precision']:.3f}", f"{base['recall']:.3f}",
                     f"{base['auc_pr']:.3f}", "reference"])
        for a in abl:
            m = a["metrics"]
            lift = (m.get("lift_over_baseline") or {}).get("auc_pr")
            rows.append([a["variant"], f"{m['precision']:.3f}", f"{m['recall']:.3f}",
                         f"{m['auc_pr']:.3f}", f"{lift:+.0f}%" if lift is not None else "—"])
        table(doc, ["Variant", "Precision", "Recall", "AUC-PR", "Lift vs baseline"], rows)
        caption(
            doc,
            f"All figures at {base['prevalence'] * 100:.3f}% prevalence on the unmodified "
            f"distribution. The baseline is a tuned gradient-boosted model given every "
            f"transaction-level feature, selected on a time-ordered tail of the training "
            f"window. The logistic regression is reported as a floor and is not what the "
            f"lift is measured against.",
        )
        graph_variant = next((a for a in abl if a["variant"] == "all_levels"), None)
        minus_graph = next((a for a in abl if a["variant"] == "all_levels_minus_graph"), None)
        if graph_variant and minus_graph:
            delta = graph_variant["metrics"]["auc_pr"] - minus_graph["metrics"]["auc_pr"]
            dr = graph_variant["metrics"]["recall"] - minus_graph["metrics"]["recall"]
            callout(
                doc,
                f"The graph level contributes +{delta:.3f} AUC-PR and "
                f"{dr * 100:+.1f} points of recall over transaction and session evidence combined.",
            )
            doc.add_paragraph(
                "The check that makes this falsifiable: all_levels_minus_graph reproduces "
                "the txn+session row to four decimal places. If the ablation were "
                "mislabelled or the feature block leaked, those two rows would differ."
            )

        doc.add_heading("5.3 Negative findings", level=2)
        doc.add_paragraph(
            "We tested two behavioural detection signals beyond amount, time and location: "
            "a coercion signature (paste-versus-type on the payee field, dwell before "
            "confirming, correction rate) and session cadence regularity. Both are visible "
            "in the ablation above. Removing either slightly improves AUC-PR."
        )
        doc.add_paragraph(
            "They are reported as negative results. No effect size was tuned at any point. "
            "A signal we invent in our own simulator is detectable by construction, so the "
            "honest test was always the ablation, and the ablation says transaction, "
            "velocity and graph evidence already carry what these two would contribute at "
            "this prevalence."
        )

    # ---------------------------------------------------------------- 6 loop
    doc.add_heading("6. The closed loop", level=1)
    doc.add_heading("6.1 The strategist located the boundary from data", level=2)
    doc.add_paragraph(
        "The red-team strategist reads the miss log, which carries SHAP contributions, and "
        "moves the simulator parameters that feed whichever feature the detector leaned on. "
        "Mutation is directed rather than random."
    )
    doc.add_paragraph(
        "Given no prior knowledge of our boundary finding, it identified the merchant-payout "
        "vector as the weakest in the set, drifted the parameter feeding that extraction, "
        "and by the third generation substituted merchant_collusion_payout with "
        "agentic_purchase — the extraction-rail axis the whole finding is about. It reached "
        "the same axis we reasoned our way to, from the data, in three generations."
    )
    if loop:
        doc.add_heading("6.2 The detection curve", level=2)
        doc.add_paragraph(
            "Three series, because the obvious one cannot be read alone. Each generation "
            "adds vectors, so the current attack set changes composition every round and "
            "its detection rate mixes 'the detector improved' with 'the mix got easier'. "
            "The fixed set holds the evaluated population constant. The new-vectors series "
            "asks whether the attacker is still getting through after the detector has "
            "seen its last idea."
        )
        rows = []
        for g in loop["generations"]:
            rows.append([
                f"G{g['generation']}",
                str(g["n_vectors"]),
                pct(g.get("detection_rate_fixed_set")),
                pct(g.get("detection_rate_new_vectors")),
                pct(g.get("detection_rate")),
                f"{g.get('n_chains_proposed', 0)} / {g.get('n_chains_rejected', 0)}",
            ])
        table(
            doc,
            ["Gen", "Vectors", "Fixed set", "New vectors", "Current set", "Proposed / rejected"],
            rows,
        )
        fixed = [g.get("detection_rate_fixed_set") for g in loop["generations"]]
        fixed = [f for f in fixed if f is not None]
        if fixed:
            spread = max(fixed) - min(fixed)
            caption(
                doc,
                f"Fixed set: generation 0's attack population scored by every generation's "
                f"model, so the population is constant and movement means the detector "
                f"moved. Spread across the run: {spread * 100:.1f} points. "
                f"Loop runs at {loop['generations'][0]['n_transactions']:,} transactions, "
                f"smaller than the headline evaluation; the two are never mixed.",
            )
        # The result section. Written from the numbers rather than around them.
        fixed_vals = [g.get("detection_rate_fixed_set") for g in loop["generations"]]
        fresh_vals = [g.get("detection_rate_new_vectors") for g in loop["generations"]]
        fixed_vals = [v for v in fixed_vals if v is not None]
        fresh_vals = [v for v in fresh_vals if v is not None]

        if fixed_vals and fresh_vals:
            mean_fixed = sum(fixed_vals[1:] or fixed_vals) / len(fixed_vals[1:] or fixed_vals)
            mean_fresh = sum(fresh_vals) / len(fresh_vals)
            gap = mean_fresh - mean_fixed

            doc.add_heading("6.3 What the loop actually showed", level=2)
            floor_fresh = min(fresh_vals)
            ceiling_reached = floor_fresh >= max(fixed_vals[1:] or fixed_vals)
            if ceiling_reached or gap > 0.02:
                callout(
                    doc,
                    "Adversarial search within a grammar hardens the defender against "
                    "variation, not against novelty.",
                )
                doc.add_paragraph(
                    f"Vectors the strategist introduced were caught at "
                    f"{floor_fresh * 100:.1f}% in the worst generation and "
                    f"{mean_fresh * 100:.1f}% on average, against "
                    f"{mean_fixed * 100:.1f}% for the fixed evaluation set over the same "
                    f"rounds. Mutations were never harder to detect than the originals."
                )
                doc.add_paragraph(
                    "The average difference understates this, because the new-vector "
                    "series sits at its ceiling. The comparison that carries the finding "
                    "is that the worst generation for fresh mutations still matched or "
                    "beat the best generation for the original set."
                )
                doc.add_paragraph(
                    "This is the boundary finding arriving from the other direction. "
                    "Mutation moves parameters and recombines primitives the grammar "
                    "already contains. It does not invent a new extraction rail, and the "
                    "extraction rail is where the boundary sits. A strategist searching "
                    "parameter space will keep producing variants of attacks the detector "
                    "has already generalised over."
                )
                doc.add_paragraph(
                    "The gap that mattered, V006, came from a rail the grammar did not yet "
                    "contain. That is a practical instruction for where to point a red "
                    "team: at new rails, not at parameter space. It is also the honest "
                    "limit of a closed loop built on a fixed vocabulary, and it argues for "
                    "expanding the primitive set between rounds rather than only mutating "
                    "within it."
                )
            else:
                doc.add_paragraph(
                    f"New vectors were caught at {mean_fresh * 100:.1f}% against "
                    f"{mean_fixed * 100:.1f}% for the fixed set, a difference of "
                    f"{gap * 100:+.1f} points. Neither series moved decisively across the "
                    f"run."
                )

        doc.add_paragraph(
            "The validation layer is reported by what it refuses, not by its acceptance "
            "rate. A 100% acceptance rate is what deterministic mutation should produce and "
            "is not evidence of anything. The evidence is the test suite, which feeds the "
            "validator backwards chains, duplicate identifiers, duplicate attack "
            "signatures, unimplemented primitives and inverted parameter ranges, and "
            "asserts each is refused for the right reason."
        )
    else:
        callout(doc, "Loop artefacts not present at build time.", WARN)

    # ---------------------------------------------------------------- 7 method
    doc.add_heading("7. Methodology, and what would invalidate these numbers", level=1)
    doc.add_paragraph(
        "Splits are by time and by account simultaneously, with an embargo window between "
        "them. No account appears in both halves and no future row trains a model evaluated "
        "on the past. Roughly 42% of rows are discarded to satisfy both conditions at once, "
        "which is the price of the protocol and is stated rather than hidden."
    )
    doc.add_paragraph(
        "AUC-PR is never compared across slices with different prevalence. The held-out "
        "slices contain one or two vectors' fraud against the same legitimate traffic, so "
        "their prevalence is roughly an eighth of the seen slice and their AUC-PR is "
        "mechanically lower. Reading those numbers against each other would have produced a "
        "large generalisation gap that was mostly a denominator."
    )
    doc.add_paragraph(
        "Detection is scored per attack instance, not per row. A card-testing sweep emits "
        "twenty rows and an authorised push payment emits one; row-weighted recall reports "
        "mostly on the noisiest vector."
    )

    doc.add_heading("7.1 Bugs that produced numbers for code that never ran", level=2)
    doc.add_paragraph(
        "Two failures of this class occurred and both were caught by a count looking wrong "
        "rather than by a test. They are recorded because they are the failure mode most "
        "likely to survive into a submission."
    )
    doc.add_paragraph(
        "First, the simulator filtered vectors against a retired registry rather than "
        "against whether their primitives were implemented. Three newly authored vectors "
        "were counted in the taxonomy, validated against the contract, and emitted nothing "
        "at all. Coverage would have been reported as 7 of 7 channels with two of those "
        "channels holding no data."
    )
    doc.add_paragraph(
        "Second, the ledger cache was keyed on seed and size but not on the attack set, so "
        "the first run after adding those vectors silently reused a ledger generated before "
        "they existed and evaluated the wrong experiment to completion."
    )
    doc.add_paragraph(
        "Both are fixed, both now have tests, and the cache key includes a digest of vector "
        "identifiers, chains, parameters and holdout flags."
    )

    # ---------------------------------------------------------------- 8 feasibility
    doc.add_heading("8. Real-world feasibility", level=1)
    if manifest:
        gen0 = manifest["generations"][0]
        m = gen0["metrics_seen"]
        rows = [
            ["Scoring latency, p50", f"{m.get('scoring_latency_p50_ms', 'n/a')} ms"],
            ["Scoring latency, p99", f"{m.get('scoring_latency_p99_ms', 'n/a')} ms"],
            ["Alert rate", pct(m["alert_rate"], 3)],
            ["Net value protected", f"INR {m.get('net_value_protected_inr', 0):,.0f}"],
            ["Review cost assumed", f"INR {manifest['cost_model']['review_cost_inr']:.0f} per alert"],
            ["Fraud base rate", pct(m["prevalence"], 3)],
        ]
        table(doc, ["Operational measure", "Value"], rows)
    doc.add_paragraph(
        "Payment authorisation budgets are measured in tens of milliseconds and the "
        "detector scores inside that. Alert rate matters more than F1 to an operator "
        "because it determines review staffing, and threshold selection is an economic "
        "optimisation over net value protected rather than an arbitrary choice."
    )
    doc.add_paragraph(
        "SHAP values are surfaced per alert in the prototype. Adverse action on a "
        "customer's transaction attracts a regulatory expectation of explanation, and a "
        "detector that cannot say why it declined is not deployable regardless of its "
        "metrics."
    )

    # ---------------------------------------------------------------- 9 scope
    doc.add_heading("9. Scope and safety boundary", level=1)
    callout(
        doc,
        "This repository generates synthetic data. It does not generate attack tooling.",
    )
    doc.add_paragraph(
        "Synthetic transaction records, session event sequences and account-graph edges, in "
        "full detail. No voice cloning, no phishing generators, no deepfake code, and "
        "nothing capable of reaching a live endpoint. Attack mechanisms are described at the "
        "level of detail needed to model their observable data footprint and no further."
    )
    doc.add_paragraph(
        "A vector named 'deepfake video-KYC bypass' produces an account row, an onboarding "
        "session with an implausibly short duration, and a graph edge. It does not produce "
        "a video."
    )

    # ---------------------------------------------------------------- 10 repro
    doc.add_heading("10. Reproduction", level=1)
    doc.add_paragraph(
        "The repository clones clean, installs from a lockfile, and regenerates every "
        "reported number from one command and one fixed seed."
    )
    p = doc.add_paragraph()
    run = p.add_run(
        "git clone https://github.com/ananyac9820/ai-defense-lab\n"
        "pip install -e \".[dev]\"\n"
        "python scripts/reproduce.py"
    )
    run.font.name = "Consolas"
    run.font.size = Pt(9.5)
    doc.add_paragraph(
        "Reference datasets are not redistributed. IEEE-CIS is competition-licensed and "
        "PaySim is large; only the derived statistical profile is committed, which also "
        "makes the single-source rule structurally true rather than merely promised."
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    doc.save(OUT)

    # Stamp what this document was built from, so the audit can verify its provenance
    # without relying on file times.
    (ARTIFACTS_DIR / "walkthrough_build.json").write_text(
        json.dumps(
            {
                "built_at": date.today().isoformat(),
                "source_digest": source_digest(),
                "run_id": (manifest or {}).get("run_id"),
                "config_hash": (manifest or {}).get("config_hash"),
                "loop_run_id": (loop or {}).get("run_id"),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return OUT


if __name__ == "__main__":
    path = build()
    print(f"wrote {path} ({path.stat().st_size / 1024:.0f} KB)")
